import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { ViewTransitions } from "next-view-transitions"

import { TanstackProvider } from "@/components/providers/tanstack-provider"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <TanstackProvider>{children}</TanstackProvider>
        </body>
      </html>
    </ViewTransitions>
  )
}
